### ISSUE TITLE
Allow room configuration

### ISSUE THREAD

**Issue by cburschka** [cburschka/cadence#101]
In order to create rooms with human-readable mixed-case titles, I added xmpp.configureRoom.

This is a powerful function that can configure any room the user has privileges to modify:
- toggle room logging
- toggle anonymity
- password protection
- toggle whether the room is listed publicly.

Currently it only ensures that the following:

```
/create This Is A Room
```

creates a room titles "This Is A Room" rather than "this\20is\20a\20room".

It would be nifty to add a CLI interface that can support at least a subset of this functionality, eg.

```
/create --hidden --anonymous --password=swordfish --log This Is A Room.
```

Or set custom title and ID explicitly:

```
/create --title="This Is A Room" room
```

Or configure an existing room:

```
/configure [room] --logged=0 --anonymous=1
```

et cetera et cetera

**Comment by cburschka** [comment]
This is the reference list of form fields for room configuration:

http://xmpp.org/registrar/formtypes.html#http:--jabber.org-protocol-mucroomconfig

For reference, here is the complete form sent by ejabberd when requesting the room configuration:

    <iq xmlns='jabber:client' from='test2@conference.calref.net' to='Arancaytar@calref.net/cadence/v1.6-calref-2-g232e74d/1422669639832' id='6:sendIQ' type='result'>
        <query xmlns='http://jabber.org/protocol/muc#owner'>
            <instructions>You need an x:data capable client to configure room</instructions>
            <x xmlns='jabber:x:data' type='form'>
                <title>Configuration of room test2@conference.calref.net</title>
                <field type='hidden' var='FORM_TYPE'>
                    <value>http://jabber.org/protocol/muc#roomconfig</value>
                </field>
                <field type='text-single' label='Room title' var='muc#roomconfig_roomname'>
                    <value/>
                </field>
                <field type='text-single' label='Room description' var='muc#roomconfig_roomdesc'>
                    <value/>
                </field>
                <field type='boolean' label='Make room persistent' var='muc#roomconfig_persistentroom'>
                    <value>0</value>
                </field>
                <field type='boolean' label='Make room public searchable' var='muc#roomconfig_publicroom'>
                    <value>1</value>
                </field>
                <field type='boolean' label='Make participants list public' var='public_list'>
                    <value>1</value>
                </field>
                <field type='boolean' label='Make room password protected' var='muc#roomconfig_passwordprotectedroom'>
                    <value>0</value>
                </field>
                <field type='text-private' label='Password' var='muc#roomconfig_roomsecret'>
                    <value/>
                </field>
                <field type='list-single' label='Maximum Number of Occupants' var='muc#roomconfig_maxusers'>
                    <value>200</value>
                    <option label='5'><value>5</value></option>
                    <option label='10'><value>10</value></option>
                    <option label='20'><value>20</value></option>
                    <option label='30'><value>30</value></option>
                    <option label='50'><value>50</value></option>
                    <option label='100'><value>100</value></option>
                    <option label='200'><value>200</value></option>
                    <option label='500'><value>500</value></option>
                </field>
                <field type='list-single' label='Present real Jabber IDs to' var='muc#roomconfig_whois'>
                    <value>moderators</value>
                    <option label='moderators only'><value>moderators</value></option>
                    <option label='anyone'><value>anyone</value></option>
                </field>
                <field type='boolean' label='Make room members-only' var='muc#roomconfig_membersonly'>
                    <value>0</value>
                </field>
                <field type='boolean' label='Make room moderated' var='muc#roomconfig_moderatedroom'>
                    <value>1</value>
                </field>
                <field type='boolean' label='Default users as participants' var='members_by_default'>
                    <value>1</value>
                </field>
                <field type='boolean' label='Allow users to change the subject' var='muc#roomconfig_changesubject'>
                    <value>1</value>
                </field>
                <field type='boolean' label='Allow users to send private messages' var='allow_private_messages'>
                    <value>1</value>
                </field>
                <field type='list-single' label='Allow visitors to send private messages to' var='allow_private_messages_from_visitors'>
                    <value>anyone</value>
                    <option label='nobody'><value>nobody</value></option>
                    <option label='moderators only'><value>moderators</value></option>
                    <option label='anyone'><value>anyone</value></option>
                </field>
                <field type='boolean' label='Allow users to query other users' var='allow_query_users'>
                    <value>1</value>
                </field>
                <field type='boolean' label='Allow users to send invites' var='muc#roomconfig_allowinvites'>
                    <value>0</value>
                </field>
                <field type='boolean' label='Allow visitors to send status text in presence updates' var='muc#roomconfig_allowvisitorstatus'>
                    <value>1</value>
                </field>
                <field type='boolean' label='Allow visitors to change nickname' var='muc#roomconfig_allowvisitornickchange'>
                    <value>1</value>
                </field>
                <field type='boolean' label='Allow visitors to send voice requests' var='muc#roomconfig_allowvoicerequests'>
                    <value>1</value>
                </field>
                <field type='text-single' label='Minimum interval between voice requests (in seconds)' var='muc#roomconfig_voicerequestmininterval'>
                    <value>1800</value>
                </field>
                <field type='jid-multi' label='Exclude Jabber IDs from CAPTCHA challenge' var='muc#roomconfig_captcha_whitelist'/>
                <field type='boolean' label='Enable logging' var='muc#roomconfig_enablelogging'>
                    <value>0</value>
                </field>
            </x>
        </query>
    </iq>

**Comment by cburschka** [comment]
The worst part of this is that I need to add command-line argument parsing to the codebase. Might be useful later on, maybe.

**Comment by cburschka** [comment]
I know! I'll do it with regular expressions!

    /\s+(--([a-z-]+)(=|\s+))?("(([^"]|\")+)"|'(([^']|\')+)'|([^"']([^\\\s]|\\\s)*))/

(Now I have two problems.)

**Comment by sylae** [comment]
Have you considered looking into PEAR repos? I've been using [Console-Getopt](http://pear.php.net/package/Console_Getopt) in my projects whenever I need to go overkill. I haven't tried it on anything other than argv, so I don't know if that's an option

**Comment by cburschka** [comment]
PEAR is exclusively PHP, isn't it?

There are Javascript libraries, but they seem to be for frameworks like nodejs.

In any case, I think I got it.

```
function(text) {
    var key = /(?:--([a-z-]+))/;
    var value = /(?:"((?:[^"]|\")+)"|'((?:[^']|\')+)'|([^"'\s](?:[^\\\s]|\\\s)*))/;
    var keyvalue = RegExp(key.source + /(?:=|\s+)/.source + value.source);
    var tokens = text.match(RegExp('\\s+(?:' + keyvalue.source + '|' + key.source + '|' + value.source + ')', 'g'));
    var arguments = {0:[]};
    console.log(tokens);
    for (var i in tokens) {
      var token = tokens[i].match(keyvalue) || tokens[i].match(key);
      if (token)
        arguments[token[1]] = token[2] || token[3] || token[4] || true;
      else {
        var token = tokens[i].match(value);
        arguments[0].push(token[1] || token[2] || token[3]);
      }
    }
    return arguments;
  }
```

**Comment by sylae** [comment]
Yeah, pear is php only. I'm a moron and forgot this is javascript :P

**Comment by cburschka** [comment]
(Eventually, it might be fun to actually *show* the form to the user - eg. in an overlay/modal dialog or something.)

**Comment by cburschka** [comment]
Okay I'm still not quite done here. Looks like any field with an empty `<value/>` doesn't get closed.

```
<?xml version="1.0" encoding="UTF-8"?>
<body xmlns="http://jabber.org/protocol/httpbind" rid="453672923" sid="f70c8e4f5d232922f072d0cd35f3a89a9fbc944c">
   <iq xmlns="jabber:client" from="Arancaytar@calref.net/cadence/v1.7-49-g327670f/1430986624438" to="test@conference.calref.net" type="set" id="30:sendIQ">
      <query xmlns="http://jabber.org/protocol/muc#owner">
         <x xmlns="jabber:x:data" type="submit">
            <field var="FORM_TYPE">
               <value>http://jabber.org/protocol/muc#roomconfig</value>
            </field>
            <field var="muc#roomconfig_roomname">
               <value>Test</value>
            </field>
            <field var="muc#roomconfig_roomdesc">
               <value />
               <field var="muc#roomconfig_persistentroom">
                  <value>1</value>
               </field>
               <field var="muc#roomconfig_publicroom">
                  <value>1</value>
               </field>
               <field var="public_list">
                  <value>1</value>
               </field>
               <field var="muc#roomconfig_passwordprotectedroom">
                  <value>0</value>
               </field>
               <field var="muc#roomconfig_roomsecret">
                  <value />
                  <field var="muc#roomconfig_maxusers">
                     <value>200</value>
                  </field>
                  <field var="muc#roomconfig_whois">
                     <value>moderators</value>
                  </field>
                  <field var="muc#roomconfig_membersonly">
                     <value>0</value>
                  </field>
                  <field var="muc#roomconfig_moderatedroom">
                     <value>1</value>
                  </field>
                  <field var="members_by_default">
                     <value>1</value>
                  </field>
                  <field var="muc#roomconfig_changesubject">
                     <value>1</value>
                  </field>
                  <field var="allow_private_messages">
                     <value>1</value>
                  </field>
                  <field var="allow_private_messages_from_visitors">
                     <value>anyone</value>
                  </field>
                  <field var="allow_query_users">
                     <value>1</value>
                  </field>
                  <field var="muc#roomconfig_allowinvites">
                     <value>0</value>
                  </field>
                  <field var="muc#roomconfig_allowvisitorstatus">
                     <value>1</value>
                  </field>
                  <field var="muc#roomconfig_allowvisitornickchange">
                     <value>1</value>
                  </field>
                  <field var="muc#roomconfig_allowvoicerequests">
                     <value>1</value>
                  </field>
                  <field var="muc#roomconfig_voicerequestmininterval">
                     <value>1800</value>
                  </field>
                  <field var="muc#roomconfig_captcha_whitelist">
                     <value />
                     <field var="muc#roomconfig_enablelogging">
                        <value>0</value>
                     </field>
                  </field>
               </field>
            </field>
         </x>
      </query>
   </iq>
</body>
```

**Comment by cburschka** [comment]
IT IS DONE
