### ISSUE TITLE
Clicking on nicks with spaces still broken

### ISSUE THREAD

**Issue by cburschka** [cburschka/cadence#124]
You'd think it'd finally work correctly after how many times I've fixed this.

Repeatedly clicking on the nick "A B" results in:

```
/msg A\ B B B B B B B B
```

**Comment by Nebedia** [comment]
http://cdn.calref.net/files.calref/31/53042fe6_untitled.PNG
Still have things like this. I was hoping this update might take care of that.

**Comment by cburschka** [comment]
At first glance, I think that's because `/kick` doesn't expect any escaped spaces. It gets only a single argument (the nickname) so there's no need for backslashes.

I could probably make it so they get ignored, though.
