### ISSUE TITLE
Inline image anchors are full-width.

### ISSUE THREAD

**Issue by cburschka** [cburschka/cadence#130]
You can click images to open them in a new tab.

Unfortunately, the resizing magic we currently do results in the link taking up the full width of the message area, regardless of image size. Clicking to the right of a small image will open the same link.

Maybe we can stop this somehow.

**Comment by Nebedia** [comment]
More on this from Chrome: http://cdn.calref.net/files.calref/31/13524f82_untitled.PNG
You can click the top x to hide the image, clicking again to un-hide the image fixes the formatting.

**Comment by cburschka** [comment]
I think this is a natural consequence of https://github.com/cburschka/cadence/blob/master/js/core/visual.js#L297

```
display:block;
```

Maybe `inline-block` would work better, this has to be checked.

**Comment by cburschka** [comment]
The biggest issue I can see is that inline images are flush with the bottom of the line, rather than vertically centered like emoticons are. But that's pretty trivial to fix.

**Comment by cburschka** [comment]
TODO: Research the CSS3 "flexbox" stuff to see if it applies to this issue. For now, simply replace "block" with "" in the line that is intended to make images visible.
