### ISSUE TITLE
/ping

### ISSUE THREAD

**Issue by Nebedia** [cburschka/cadence#150]
Not sure how possible this is with XMPP, but we used to have this feature before and it would be nice to have it again to rapidly check for server lag.

**Comment by cburschka** [comment]
http://xmpp.org/extensions/xep-0199.html

**Comment by cburschka** [comment]
Defined by the standard:

```
<iq from='juliet@capulet.lit/balcony' to='capulet.lit' id='c2s1' type='get'>
  <ping xmlns='urn:xmpp:ping'/>
</iq>
```

What happens if I try this:
```
<iq from='Arancaytar@calref.net/cadence/v1.5-calref/1421651732571' to='calref.net' type='get' xmlns='jabber:client'>
   <ping xmlns='urn:xmpp:ping'/>
</iq>

<iq xmlns='jabber:client' from='calref.net' to='Arancaytar@calref.net/cadence/v1.5-calref/1421651732571' type='error'>
   <ping xmlns='urn:xmpp:ping'/>
   <error code='501' type='cancel'>
      <feature-not-implemented xmlns='urn:ietf:params:xml:ns:xmpp-stanzas'/>
   </error>
</iq>
```

**Comment by cburschka** [comment]
Oh, and ejaberd ostensibly supports ping: http://www.process-one.net/en/ejabberd/protocols/

**Comment by cburschka** [comment]
Since 2.1.0, apparently.  https://support.process-one.net/browse/EJAB-974

Maybe the module (mod_ping) is not enabled by default; @sylae might check the ejabberd config.

**Comment by sylae** [comment]
@sylae enabled that, hopefully should work for your 'testing' now.

**Comment by cburschka** [comment]
:yay: !

**Comment by cburschka** [comment]
Still getting an error, actually.

Not that it matters, really. For a ping response, "pong" and "ping is not supported" are basically the same thing.

**Comment by cburschka** [comment]
Wait, never mind; the reason was probably me fucking up while sending this stuff manually. It works now that I'm doing it right.

**Comment by cburschka** [comment]
Follow-up: #151
