### ISSUE TITLE
Permanent Aliases - /online /action

### ISSUE THREAD

**Issue by Nebedia** [cburschka/cadence#153]
I'm pretty oldschool, so after using AJAX for five years, I'm still pretty accustomed to using these commands and, unfortunately, whenever I clear my cookies or switch to a new device (which is remarkably often), these settings die. So I would appreciate it if they could be added in as built-in aliases, similarly to the way :wingboner: has a hidden alias to call :rdsitting: in the ponicon section.

Normally, I would just copy the /back and /me commands in chat.js and add in new sections that had /online and /action instead. But I also understand that you're German and this is probably extremely inefficient, so I'm probably better off leaving it up to you.

**Comment by cburschka** [comment]
Well, config.settings.aliases is a settings key, and those can have default values.

**Comment by cburschka** [comment]
In fact, we can add this to config.tpl.js in the calref branch:

```
@@ -62,7 +62,7 @@ var config = {
resource: '{client}/{version}/{timestamp}',
},
- macros: {},
+ macros: {online: '/back', action: '/me'},
version: '@@@VERSION@@@',
},
```

**Comment by Nebedia** [comment]
Thanks. :D
