### ISSUE TITLE
Long chat lines occasionally push delete button down

### ISSUE THREAD

**Issue by sylae** [cburschka/cadence#165]
see image: https://c312441.ssl.cf1.rackcdn.com/sylae/images/misc/3bb98a374378f1d747ab9cc49788d64c.png

Adding a margin-right or padding-right to the span seems to fix it.

**Comment by cburschka** [comment]
What element are you changing to fix it? I have tried to set margin-right on span.body, and while it makes the message wrap earlier it still pushes the delete button down with its invisible box. padding-right doesn't work either.

**Comment by cburschka** [comment]
I may have fixed it just by rearranging the markup so the float element comes first.

Probably should've remembered this from back when I was first dicking around with wiki markup ten years ago and ran into a similar issue. :P
