### ISSUE TITLE
Full RGB color thing is glitchy

### ISSUE THREAD

**Issue by cburschka** [cburschka/cadence#166]
It works properly once the RGB color has been set, but the "press for 0.5 seconds" thing doesn't seem to work right and requires a few attempts followed by clicking on the label itself. Tested in Firefox.

**Comment by cburschka** [comment]
Current state model:

* "None" state: Clicking on None brings up the palette both in full color mode and palette mode. Holding the button activates full color mode but does not open the color selector.
* Color selected: Clicking on the color button brings up the palette in palette mode, and the selector in full color mode. Holding the button activates full color mode but does not open the selector.

**Comment by cburschka** [comment]
Well, it's one bug, actually. Clicking on "None" intentionally opens the palette regardless of mode, because you can open the selector and cancel, which still leaves you in full color mode without a color set. You then couldn't go back to palette mode without first selecting a color and clearing it, which would be really weird.

The actual bug, of course, is that the selector doesn't open on the mouse-hold event in the first place.

**Comment by cburschka** [comment]
There *is* a second bug, in that if you are in phantom full-color mode, you can open the palette and select a color only once - clicking again will open the full color selector instead.

So full-color mode should be unset by selecting a palette color.

**Comment by cburschka** [comment]
There is also a third bug, which is that you can bring up the full color selector immediately by clicking the label.

**Comment by cburschka** [comment]
The latter two are easy to fix, but I'm pretty stumped by the first.

**Comment by cburschka** [comment]
For reference: http://stackoverflow.com/questions/28864557/triggering-a-click-event-in-a-timeout-function

**Comment by sylae** [comment]
Why not have an ellipsis or something at the end of the palette that opens the full-color selector? Or a dropdown triangle or some shit.

**Comment by cburschka** [comment]
That would actually be a good idea. Since the full-color setting is sticky (the only way to get back to the palette is to clear the setting) that extra click is really not significant.

**Comment by cburschka** [comment]
> There is also a third bug, which is that you can bring up the full color selector immediately by clicking the label.

This is now fixed by #188.

**Comment by cburschka** [comment]
> So full-color mode should be unset by selecting a palette color.

This is a one-line patch.

**Comment by cburschka** [comment]
Oops. Now I remember why I didn't put the control in the palette originally - it's not supposed to show up when you're using the [color] BBCode button.

**Comment by cburschka** [comment]
Have to amend this slightly.

**Comment by cburschka** [comment]
Silly github, reverting a commit with "Fix ..." in it should maybe *reopen* the issue, not close it. <_<
