### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by cburschka** [cburschka/cadence#167]
Desktop notifications are supported by most current browsers: http://www.w3.org/TR/notifications/

So is checking if a tab is currently visible: http://www.w3.org/TR/page-visibility/

It would be nice to enable pop-ups for certain messages to avoid having to tab over. This could be set to several levels: 

* None
* Private messages and keyword mentions
* All messages
* All messages and notifications

Obviously, notifications would only be generated when the tab is in the background.

**Comment by cburschka** [comment]
IT'S HAPPENING

**Comment by sylae** [comment]
Just noticed an issue with these while trying them out: It escapes HTML on nightly firefox. Guessing that notifications don't support HTML, so perhaps that should be stripped?

![Picture](https://c312441.ssl.cf1.rackcdn.com/sylae/images/misc/66217efd688ddb721f6ef6ce8583ac20.png)

`Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:40.0) Gecko/20100101 Firefox/40.0` built from https://hg.mozilla.org/mozilla-central/rev/77d92f6d7679

**Comment by cburschka** [comment]
Ouch. I was relying on a gnome-specific specification: https://people.gnome.org/~mccann/docs/notification-spec/notification-spec-latest.html

I'm guessing that markup isn't part of the standard.
