### ISSUE TITLE
/Who Needs Some Help

### ISSUE THREAD

**Issue by Nebedia** [cburschka/cadence#179]
https://c312441.ssl.cf1.rackcdn.com/files.calref/31/d6a09285_untitled.PNG
Well, this is no better. 
Would it be possible to replace the obvious current PDNs with their UID?
Also make note of the comma at the end that shouldn't be there.

**Comment by cburschka** [comment]
In fact, the string ends with a period. If it isn't there, that means the message is incomplete for whatever reason.
