### ISSUE TITLE
'dnd' presence

### ISSUE THREAD

**Issue by sylae** [cburschka/cadence#182]
Allow clients to set themselves as "do not disturb" presence. This could have a number of nifty features such as:

* Muting all sounds if you are dnd'ed.
* An icon in the sidebar, similar to the feet (maybe greyed out feet (probably better for xa?) or a big no sign or something.
* Probably other stuff, but I can't think and I am sleppy.

**Comment by cburschka** [comment]
Yeah.

/dnd?

(Should note that reliably turning off sounds also means locally storing the status. Right now, /away and /back do nothing except send a presence to the server, which might not have an effect if you're logged in elsewhere.)

**Comment by cburschka** [comment]
With @sylae's commits, the only thing left is the local status tracking and sound blocking. Oh, and of course the desktop notifications from #167 should be blocked too.

**Comment by cburschka** [comment]
Well, not quite - ui.notify() calls both ui.playSound() and ui.notifyDesktop(), but it's not the only caller for either of them. The latter two functions should be the ones to block the event.
