### ISSUE TITLE
Preview for Chat Sounds

### ISSUE THREAD

**Issue by Nebedia** [cburschka/cadence#218]
Here's a low-priority feature/enhancement that comes from the old AJAX version.

Currently, it's relatively inconvenient to set your chat sounds if you do not already know what they are. In order to test them, you would need to do something to the effect of setting them as your private message sounds and then send a message to yourself for each sound.

An easy solution would be to attach some kind of preview button next to the audio settings, so you can preview the sound after making your selection.
See: https://c312441.ssl.cf1.rackcdn.com/files.calref/31/a2583710_untitled.PNG

**Comment by cburschka** [comment]
Yep, that looks good. Conveniently, even the unused playback icon is still in the repository (missed it during #198 because it looked like the autoscroll icon).
