### ISSUE TITLE
Being /away now hides flare in chat messages.

### ISSUE THREAD

**Issue by Nebedia** [cburschka/cadence#259]
Nice job getting chatbot messages to display flare, by the way. However, there's a new bug.

Whereas before the away icon would conflict with flare in the online user pane (effectively replacing it), but leave chat messages unaffected, chat messages now have no icons at all next to the username when a member is away:

https://c312441.ssl.cf1.rackcdn.com/files.calref/31/abe3d702_untitled.PNG

**Comment by sylae** [comment]
This should be a pretty easy fix with a second CSS rule for each flair. I'll push an update on the calref branch tonight.

**Comment by sylae** [comment]
this is fixed in commit 971bc812f01c430c915ea3568c6c78708ac483a4 on the calref branch
