### ISSUE TITLE
Update libraries

### ISSUE THREAD

**Issue by cburschka** [cburschka/cadence#277]
* [jquery-contextmenu](/medialize/jQuery-contextMenu) is now at 2.0.0 (we're using 1.6.7)
* [js-cookie](/js-cookie/js-cookie) is at 2.0.4 (we're using 1.5.1)
* [filesaver](/eligrey/FileSaver) has no releases, but has 18 new commits.
* [moment](/moment/moment) is at 2.10.6 (we're using 2.10.2)
* [strophe](/strophe/strophejs) is at 1.2.3 (we're using 1.2.1)

**Comment by cburschka** [comment]
Everything but contextmenu and cookie are minor updates that should be straightforward.

**Comment by cburschka** [comment]
contextmenu class markup has changed a bit, requiring an update to the CSS.

**Comment by cburschka** [comment]
NOPE

![screenshot from 2015-11-28 15 23 03](https://cloud.githubusercontent.com/assets/1448001/11452318/f4bc7230-95e3-11e5-8dca-bb7eec202df6.png)

**Comment by sylae** [comment]
Looks like a great new theme idea to me! :)

**Comment by cburschka** [comment]
Apparently they're doing the whole web font/icon glyph thing that's all the rage now. You're supposed to do stuff like `icon: before { content: "<U+0000>"; }` now.

Which wouldn't *technically* be infeasible since afaik the icons we're using all have publically available vectors, but it would really complicate the build process.

**Comment by cburschka** [comment]
The web font thing is now #442.

It'll effectively change the UI (by switching from full-color Tango bitmap icons to monochrome vector glyphs), so it's more of a 3.0 redesign move.
