### ISSUE TITLE
Move Symotes, etc, to calref branch

### ISSUE THREAD

**Issue by sylae** [cburschka/cadence#280]
I guess the long-term goal is not having ponies in cadence (for shaaaame), but even if ponicons are a separate package, it might be in the interest to get the OCs out of there.

And Gin.

**Comment by cburschka** [comment]
Good idea... they don't even necessarily have to form a separate pack, since the pack is still inside the repository.

(The first merge after they're removed will be a bit finicky, since we need to merge the deletion commit without actually deleting them, but after that it won't be an issue.)

**Comment by cburschka** [comment]
While at it, I think the VS ones with non-canon art styles should probably be moved out too.

And me, obviously. :P

**Comment by sylae** [comment]
and :gin: and probably the berries as well.

PURGE ALL THE EMOTES.
