### ISSUE TITLE
A handful more ponicons

### ISSUE THREAD

**Issue by sylae** [cburschka/cadence#283]
I tried cherry-picking the commit to do a pull request but I'm stupid and I don't know what I'm doing.

Anyway, behold. 11 new ponicons, and a replacement for the...kinda ugly :vscry: emote.

https://github.com/calref/cadence/commit/8fc6184ce3f32373cdce968813c55917bce8c10a

**Comment by cburschka** [comment]
:aaaaa:

I hope I merged it in correctly. calref emoticons.conf diverged from upstream quite a bit now
