### ISSUE TITLE
Be a tiny bit smarter with URL parsing.

### ISSUE THREAD

**Issue by cburschka** [cburschka/cadence#289]
Sometimes URLs have punctuation after them. Sometimes URLs have punctuation inside them.

The parser currently distinguishes between these cases by allowing punctuation inside URLs but not at the end.

One specific case is problematic, and that is wiki-style disambiguation, which puts parenthesized words at the end of the URL. This is pretty much the only case where a URL ends in punctuation.

We could recognize this special case and allow the URL to have *one* close-paren at the end if and only if it also contains an open-paren.

**Comment by cburschka** [comment]
Note: 

github does this: https://github.com/cburschka/cadence/blob/master/js/core/visual.js)

and this: https://github.com/cburschka/cadence/blob/master/js/core/visual.js_(test)

**Comment by sylae** [comment]
You know, you could just support `[url]http://example.com[/url]` out of the box.

users expect that,  we can not and should not force users to adapt to cadence.

I mean, have you even tried inputting `[url]example.org[/url]`?

It does not work.

**Comment by cburschka** [comment]
ಠ_ಠ

**Comment by cburschka** [comment]
I think this is what GitHub uses to do what it does: https://github.com/vmg/redcarpet/blob/master/ext/redcarpet/autolink.c#L100

(Obviously, with a one-line regex, we won't really match up to the power of C.)

**Comment by cburschka** [comment]
I think I have something that'll cover this use-case:

* still require URLs to end with `a-zA-Z0-9_-=/`, but search for any number of `)` after that.
* count the unclosed parentheses in the URL
* add up to that many of the found `)` to the URL, and leave the rest.
