### ISSUE TITLE
Switch to \HEX for escaping NULL and whitespace in class names.

### ISSUE THREAD

**Issue by sylae** [cburschka/cadence#298]
If i log in as `username with spaces@calref.net`, I am getting inconsistent escaping of the spaces in question:
```html
<span class="user user-role-participant user-affiliation-none
  jid-node-username\32with\32spaces jid-domain-calref.net
  jid-resource-cadence/v1.10.0-calref-6-gf8ba682/1450943259102 user-show-default"
  data-affiliation="none" data-nick="username with spaces"
  data-jid="username\20with\20spaces@calref.net/cadence/v1.10.0-calref-6-gf8ba682/1450943259102"
  title="username\20with\20spaces@calref.net/cadence/v1.10.0-calref-6-gf8ba682/1450943259102"
>username with spaces</span>
```

Is this intentional?

**Comment by cburschka** [comment]
I'll have to check it's the right way each time and that I read the
standards correctly, but basically yes. \20 is hexadecimal (specified by
XMPP) and \32 is decimal (for CSS) for the same character code.

(Yeah, the standards are kind of weird)

**Comment by cburschka** [comment]
Also, I think I dreamed the last one up. There is a method of escaping characters in CSS code (which uses hexadecimal), but seemingly no way of escaping class names as used by jQuery and HTML attributes. Presumably you're supposed to use the unescaped class names there, and they can't contain spaces at all.

Which means that any escaping is purely on me, and I might as well use hexadecimal. :)
