### ISSUE TITLE
Moar Starlight Glimmer.

### ISSUE THREAD

**Issue by TrentonOfCalref** [cburschka/cadence#352]
We obviously don't have enough Starlight Glimmer Ponicons. Since there is a brand new season apon us, and considering she is new best pony, this must be remedied. Since she's going to be a secondary character protagonist now at the least and a continuing part of Twilight's and the Gangs adventures, we need more of her in chat.

Also, :twibeam: needs to be changed to :books: , as this is the only thing that  could make Twilight beam so much in the first place! Plus, it's shorter and easier to remember.

**Comment by cburschka** [comment]
> best pony

She's just a Sunset Shimmer rip-off, you heathen.

But sure, whatever, more ponicons. I'll check /r/mylittlepony and ~~/r/sunsetshimmer~~ I mean /r/starlightglimmer for some candidates.

IT SHOULD'VE BEEN SUNSET

MY POOR OTP

:P

**Comment by cburschka** [comment]
> :twibeam: needs to be changed to :books:

Until I checked the chatlog, I thought you were legitimately suggesting replacing the current :twibeam: image with that pile of books. :P

**Comment by cburschka** [comment]
Calref has a lot of funny ponicon aliases (check https://github.com/calref/cadence/tree/master/emoticon-packs/emoticons.conf), so :books: could be added to that.

**Comment by cburschka** [comment]
/r/starlightglimmer is basically this: 

![](https://b.thumbs.redditmedia.com/GqeM9neghDalCfMFmoKsqgfcrHEvi_h6LY11y0hdy0M.png)

**Comment by cburschka** [comment]
And then there's /r/glimmerquisition:

![](https://b.thumbs.redditmedia.com/SqQhnmdK2D6f0LXU634919sajdwWf99UsYlZSGbfClA.png)

**Comment by TrentonOfCalref** [comment]
But who cares about Moondancer? :P 
/r/StarlightGlimmer
The top left would make a good one. :sgcondescending:?  Bottom left could be :sgscrunch:

/r/glimmerquisition

The second row, 4th column , and/or 1st column second row. rage is always a good candidate. 

https://cdn.calref.net/files.calref/524/5a197e4e_sg.png
What is this face supposed to be representing? Disgust? Uncertainty? Either way, I like it. It's unique enough to be used occasionally.

Also: http://img12.deviantart.net/18e2/i/2016/007/9/c/starlight_glimmer__clapping_vector__by_davidsfire-d9n4257.png

THIS. FACE. RIGHT. HERE.

Other than that, not a lot of these stick out here. A few of them seem okay for generic glad, or smile, or stuff, but those are already covered by MANY other ponicons.

**Comment by cburschka** [comment]
There's some palette mismatch between those two sheets, by the way. I'll have to check if I can find a color guide to see which shade of purple she's supposed to be.

**Comment by cburschka** [comment]
According to http://helmet.kafuka.org/ponycolors/#starlightglimmer, the paler shade is the right one. It's eebef3.

**Comment by cburschka** [comment]
The rage and that last one are already :shutup: and :goodjob: . I'm adding :sgfacehoof: (5,2 from /r/starlightglimmer) and :sgsmug: (1,1 /r/starlightglimmer) and :sgpopcorn: (straight from /r/mylittlepony F-table) so far.

For https://cdn.calref.net/files.calref/524/5a197e4e_sg.png, I'm thinking :sgponder: (as with :twiponder: and :nebponder:) even though her stare is a bit more disapproving.

**Comment by cburschka** [comment]
/r/starlightglimmer has greatly expanded their selection. (And also fixed their palette.)

https://b.thumbs.redditmedia.com/0iCxxt5MJq0ddff6ESxMvdaxfGPdrTfq2mPjxpH7BMo.png
