### ISSUE TITLE
Implimentation of XEP-0092 does not allow users to deny OS sharing

### ISSUE THREAD

**Issue by sylae** [cburschka/cadence#394]
https://xmpp.org/extensions/xep-0092.html#security

> Revealing the application's underlying operating system may open the user or system to attacks directed against that operating system; therefore, an application MUST provide a way for a human user or administrator to disable sharing of information about the operating system.

**Comment by cburschka** [comment]
This solution falls short, actually, because the setting is only checked on startup (when the version plugin is initialized). That's weird and counter-intuitive compared to how all the other settings work.

Solution: Reinitialize the plugin whenever the setting is changed.
