### ISSUE TITLE
Send presence stanza on login

### ISSUE THREAD

**Issue by sylae** [cburschka/cadence#422]
Cadence currently seems to only send presence stanzas in the MUC context -- leaving and joining rooms. As there is now /dmsg support, it would be nice to allow people on third-party clients (like, say Conversations on their phone) to see whether or not a user in their roster is online or not, so they know if sending a non-MUC message will be delivered.
![untitled](https://cloud.githubusercontent.com/assets/2791628/17834049/4366d056-66fe-11e6-80ab-124b6773bff6.png)

**Comment by sylae** [comment]
Wait, I'm stupid. Cadence needs to let me subscribe to presence updates? I dunno how any of that works to be honest :package:

**Comment by cburschka** [comment]
Yeah, cadence doesn't currently have any way to handle contacts. It sends a presence broadcast which the server forwards to all your contacts (and the server sends *you* the presences of all your contacts) but there is no way to add/remove subscriptions, nor to show currently online contacts. It's part of the planned 3.0 stuff with tabbed rooms etc. (making it a full client and not just a single-room one).
