### ISSUE TITLE
Second attempt at logging in hangs if first attempt's password was incorrect

### ISSUE THREAD

**Issue by sylae** [cburschka/cadence#452]
>(16:58:42) Connecting...
>(16:58:42) Authentication failed.
>(16:58:49) Connecting...

sits at Connecting... forever

Looking into it, the first attempt sends...

```xml
<body rid='804993653' xmlns='http://jabber.org/protocol/httpbind' sid='...'>
  <auth xmlns='urn:ietf:params:xml:ns:xmpp-sasl' mechanism='PLAIN'>...</auth>
</body>
```

RX:

```xml
<body xmlns='http://jabber.org/protocol/httpbind'>
  <failure xmlns='urn:ietf:params:xml:ns:xmpp-sasl'>
    <not-authorized/>
  </failure>
</body>
```

The second attempt (and all future) send what appears to be just a keepalive for bosh?...

```xml
<body rid='804993654' xmlns='http://jabber.org/protocol/httpbind' sid='...' to='calref.net' xml:lang='en' wait='60' hold='1' content='text/xml; charset=utf-8' ver='1.6' xmpp:version='1.0' xmlns:xmpp='urn:xmpp:xbosh'/>
```

RX:

```xml
<body xmlns='http://jabber.org/protocol/httpbind'/>
```

also AAAAAAAAA i hit login again and now cadence is making four requests a second of the above second attempt keepalive thing.

**Comment by cburschka** [comment]
Oops. Pretty devastating bug, and it seems to persist with the latest stable versions of both ejabberd and strophe. BOSH-specific.
