### ISSUE TITLE
User context menu.

### ISSUE THREAD

**Issue by cburschka** [cburschka/cadence#5]
Ajax-Chat has a context menu (actually an expanding submenu) on each user in the user list with some command shortcuts like /msg, /kick, /nick, /invite, etc.

Once /msg ( #2 ), invite and maybe moderator support is in, a jQuery-based context menu would be a neat idea; maybe activated on right-click.

**Comment by cburschka** [comment]
http://medialize.github.io/jQuery-contextMenu/demo/trigger-hover-autohide.html

**Comment by Nebedia** [comment]
I might recommend trigger: 'left' (or right, as you initially suggested) instead of trigger: 'hover'.

**Comment by cburschka** [comment]
By the way: Firefox overrides the right-click capture if you hold down shift, which is very useful if you want to access the regular context menu.
